spring:
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}
  concurrency:
    tracker:
      ttl-seconds: ${REDIS_CONCURRENCY_TRACKER_TTL_SECONDS:60}
