spring:
  cloud:
    function:
      definition: driveFileCreatedIntegrationConsumer;createFileCommandConsumer
    stream:
      function:
        bindings:
          driveFileCreatedIntegrationConsumer-in-0: fileCreatedIntegration-in-0
          driveFileCreatedIntegrationConsumer-in-1: fileCreatedIntegrationRetry-in-0
          createFileCommandConsumer-in-0: createFileCommand-in-0
      default:
        content-type: application/json
      bindings:

        ###### -------- DOMAIN EVENTS -------- ######
        ## SpringCloud bindings                    ##

        ## --------------------------------------- ##

        ###### ------ PRIVATE MESSAGES ------- ######
        ## Create File --------------------------- ##
        # Outgoing -> Create File                   #
        createFileCommand-out-0:
          destination: command.exchange
        # Outgoing -> Create File (error)           #
        createFileCommandError-out-0:
          destination: command.exchange.error
          producer:
            requiredGroups: command:create-file.queue.error
        # Incoming <- Create File                   #
        createFileCommand-in-0:
          destination: command.exchange
          group: command:create-file.queue
          consumer:
            max-attempts: 1
            concurrency: 1 #${application.messaging.private.consumer.create-file.concurrency}
        ## --------------------------------------- ##

        ###### -------- PUBLIC MESSAGES -------- ######
        ## ----------------------------------------- ##
        # Incoming <- File Created Integration ----   #
        fileCreatedIntegration-in-0:
          binder: public-binder
          destination: integration.exchange
          group: storage.drive.file.created.queue
          consumer:
            max-attempts: 1
            concurrency: ${application.messaging.public.consumer.drive-file-created.concurrency}
        # Outgoing -> File Created Integration (error) #
        fileCreatedIntegrationError-out-0:
          binder: public-binder
          destination: storage.exchange.error
          producer:
            requiredGroups: storage.drive.file.created.queue.error
        ## File Created Integration (retry) --------- ##
        # Incoming <- File Created Integration (retry) #
        fileCreatedIntegrationRetry-in-0:
          binder: public-binder
          destination: storage.exchange
          group: storage.drive.file.created.queue.retry
          consumer:
            max-attempts: 1
            concurrency: ${application.messaging.public.consumer.drive-file-created.concurrency}
        ## ------------------------------------------ ##
        driveFileCreated-in-0:
          binder: public-binder
          destination: integration.exchange
          group: storage.drive.file.created.queue.old
          consumer:
            max-attempts: 1
            concurrency: ${application.messaging.public.consumer.drive-file-created.concurrency}
        ## --------------------------------------- ##
        # Outgoing -> File Upload Completed         #
        driveFileCreatedError-out-0:
          binder: public-binder
          destination: storage.exchange.error
          producer:
            requiredGroups: storage.drive.file.created.queue.error
        ## --------------------------------------- ##
