spring:
  cloud:
    stream:
      binders:
        private-binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${rabbitmq.host}
                port: ${rabbitmq.port}
                virtual-host: ${rabbitmq.private-virtual-host}
                username: ${rabbitmq.username}
                password: ${rabbitmq.password}
        public-binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${rabbitmq.host}
                port: ${rabbitmq.port}
                virtual-host: ${rabbitmq.public-virtual-host}
                username: ${rabbitmq.username}
                password: ${rabbitmq.password}
      default-binder: private-binder
      rabbit:
        bindings:

          ###### (INIT) DOMAIN EVENTS
          ## ...
          ###### (END) DOMAIN EVENTS

          ###### (INIT) PRIVATE COMMANDS
          ## (INIT) Create-File
          # OUT -> Create-File
          createFileCommand-out-0:
            producer:
              exchangeType: topic
              routingKeyExpression: "'create-file'"
          # OUT -> Create-File (error)
          createFileCommandError-out-0:
            producer:
              exchangeType: topic
              routingKeyExpression: "'create-file'"
              queueNameGroupOnly: true
          # IN <- Create-File
          createFileCommand-in-0:
            consumer:
              exchangeType: topic
              bindingRoutingKey: create-file
              queueNameGroupOnly: true
              autoBindDlq: true
              deadLetterExchange: command.exchange.wait
              deadLetterQueueName: command:create-file.queue.wait
              dlqDeadLetterExchange: command.exchange
              dlqDeadLetterRoutingKey: create-file
              republishToDlq: false
              dlqTtl: 1000
          ## (END) Create-File
          ## (INIT) Publish-File
          # OUT -> Publish-File
          publishFileCommand-out-0:
            producer:
              exchangeType: topic
              routingKeyExpression: "'publish-file'"
          # OUT -> Publish-File (error)
          publishFileCommandError-out-0:
            producer:
              exchangeType: topic
              routingKeyExpression: "'publish-file'"
              queueNameGroupOnly: true
          # IN <- Publish-File
          publishFileCommand-in-0:
            consumer:
              exchangeType: topic
              bindingRoutingKey: publish-file
              queueNameGroupOnly: true
              autoBindDlq: true
              deadLetterExchange: command.exchange.wait
              deadLetterQueueName: command:publish-file.queue.wait
              dlqDeadLetterExchange: command.exchange
              dlqDeadLetterRoutingKey: publish-file
              republishToDlq: false
              dlqTtl: 1000
          ## (END) Publish-File
          ###### (END) PRIVATE COMMANDS

          ##### (INIT) INTEGRATION MESSAGES
          ## (INIT) File Publication Finalized
          # OUT -> File Publication Finalized
          filePublicationFinalizedIntegration-out-0:            
            producer:
              exchangeType: topic
              routingKeyExpression: "'drive.file:publication.finalized'"
          ## (END) File Publication Finalized
          ### (INIT) DRIVE
          ## (INIT) File Created (DRIVE)
          # IN <- file created integration (DRIVE)
          driveFileCreatedIntegration-in-0:
            consumer:
              exchangeType: topic
              bindingRoutingKey: drive.file.created
              queueNameGroupOnly: true
              autoBindDlq: true
              deadLetterExchange: storage.exchange.wait
              deadLetterQueueName: storage.drive.file.created.queue.wait
              dlqDeadLetterExchange: storage.exchange
              dlqDeadLetterRoutingKey: drive.file.created
              republishToDlq: false
              dlqTtl: 1000
          # OUT -> File Created Integration [error]
          driveFileCreatedIntegrationError-out-0:
            producer:
              exchangeType: topic
              routingKeyExpression: "'drive.file.created'"
              queueNameGroupOnly: true
          ## (END) File Created (DRIVE)
          ## (INIT) File Publication Initiated (DRIVE)
          # IN <- File Publication Initiated Integration (DRIVE)
          driveFilePublicationInitiatedIntegration-in-0:
            consumer:
              exchangeType: topic
              bindingRoutingKey: drive.file:publication.initiated
              queueNameGroupOnly: true
              autoBindDlq: true
              deadLetterExchange: storage.exchange.wait
              deadLetterQueueName: storage.drive.file:publication.initiated.queue.wait
              dlqDeadLetterExchange: storage.exchange
              dlqDeadLetterRoutingKey: drive.file:publication.initiated
              republishToDlq: false
              dlqTtl: 1000
          # OUT -> File Publication Initiated Integration [error]
          driveFilePublicationInitiatedIntegrationError-out-0:
            producer:
              exchangeType: topic
              routingKeyExpression: "'drive.file:publication.initiated'"
              queueNameGroupOnly: true
          ## (END) File Publication Initiated (DRIVE)
          ### (END) DRIVE
          ##### (END) INTEGRATION MESSAGES

rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}
  private-virtual-host: ${RABBITMQ_PRIVATE_VIRTUAL_HOST:/}
  public-virtual-host: ${RABBITMQ_PUBLIC_VIRTUAL_HOST:/}
  username: ${RABBITMQ_USERNAME:rabbitmq}
  password: ${RABBITMQ_PASSWORD:rabbitmq}
