server:
  port: ${application.server.port}
spring:
  profiles:
    active:
      - spring-cloud
      - hibernate
      - ${application.vendor.messaging}
      - ${application.vendor.concurrency-tracker}
      - ${application.vendor.database}
      - ${application.vendor.storage}

application:
  name: storage-api
  server:
    port: ${SERVER_PORT:8080}
  transfer-channel:
    upload:
      chunk-size-bytes: ${TRANSFER_CHANNEL_UPLOAD_CHUNK_SIZE:10485760} # 10MB
      chunk-max-parallel: ${TRANSFER_CHANNEL_UPLOAD_MAX_PARALLEL_UPLOADS:10}
      chunk-max-bytes-per-second: ${TRANSFER_CHANNEL_UPLOAD_MAX_BYTES_PER_SECOND:1048576} # 1MB/s
    download:
      chunk-size-bytes: ${TRANSFER_CHANNEL_DOWNLOAD_CHUNK_SIZE:10485760} # 10MB
      chunk-max-parallel: ${TRANSFER_CHANNEL_DOWNLOAD_MAX_PARALLEL_DOWNLOADS:10}
      chunk-max-bytes-per-second: ${TRANSFER_CHANNEL_DOWNLOAD_MAX_BYTES_PER_SECOND:1048576} # 1MB/s
  messaging:
    private:
      consumer:
        file-upload-transfer-channel-completed:
          concurrency: ${CONSUMER_FILE_UPLOAD_TRANSFER_CHANNEL_COMPLETED_CONCURRENCY:1}
          max-attempts: ${CONSUMER_FILE_UPLOAD_TRANSFER_CHANNEL_COMPLETED_MAX_ATTEMPTS:5}
    public:
      consumer:
        drive-file-created:
          concurrency: ${CONSUMER_DRIVE_FILE_CREATED_CONCURRENCY:1}
          max-attempts: ${CONSUMER_DRIVE_FILE_CREATED_MAX_ATTEMPTS:5}
  outbox:
    relay:
      fixed-rate: ${OUTBOX_RELAY_FIXED_RATE:60000}
  vendor:
    concurrency-tracker: ${VENDOR_CONCURRENCY_TRACKER:inmemory}
    database: ${VENDOR_DATABASE:h2}
    storage: ${VENDOR_STORAGE:fs}
    messaging: ${VENDOR_MESSAGING:rabbitmq}
