plugins {
    id 'java'
}

group = 'org.osnormais'
version = '1.0-SNAPSHOT'

dependencies {

    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.4'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.19.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
}
