plugins {
    id 'java-conventions'
    id 'application'
    alias(libs.plugins.spring.boot)
}

bootJar {
    archiveFileName = 'application.jar'
    destinationDirectory = file("${rootProject.buildDir}/libs")
}

def gav = { group, name, versionRef ->
    "${group}:${name}:${versionRef.get()}"
}

dependencies {

    implementation(project(':domain'))
    implementation(project(':application'))

    implementation platform(gav('org.springframework.boot', 'spring-boot-dependencies', libs.versions.spring.boot))

    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.2'

    implementation 'commons-io:commons-io:2.21.0'
    implementation 'commons-codec:commons-codec:1.20.0'

}
